# Conclusion {#chap-conclusion}

The R and RStudio work environment allows for the production of all types of documents with a single language.

The objective of reproducibility of results is achieved by integrating statistical processing and writing. 
Collaborative work is allowed by the systematic use of source control and GitHub.
The presentation of results is ensured by GitHub pages and document templates covering most needs.

For breaks, R even provides some games in the **fun** package, including the famous Minesweeper:

```{r mine_sweeper, eval=FALSE}
# Install the package
install.packages("fun")
# Open an X window and run
if (interactive()) {
    if (.Platform$OS.type == "windows") 
        x11() else x11(type = "Xlib")
    fun::mine_sweeper()
}
```

This document does not aim to be exhaustive on the possibilities of R but rather to present a working method and simple ways to apply it quickly.
You can refer to the more detailed works cited in the text to go deeper into a particular point.

It is updated regularly as the available tools evolve.
